steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/artifact-399517/website-tools/website-image', '.']
  

images:
- 'us-central1-docker.pkg.dev/artifact-399517/website-tools/website-image'
